// <auto-generated />
using System;
using Financials.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financials.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancialsDbContext))]
    [Migration("20260508160026_AddOverCommitmentGuard")]
    partial class AddOverCommitmentGuard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fin")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Financials.Domain.Budgets.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<Guid>("FinancialsProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialsProjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_Budgets_FinancialsProjectId");

                    b.ToTable("Budgets", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Budgets.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BudgetRevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CimsCostCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkPackage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CimsCostCodeId")
                        .HasDatabaseName("IX_BudgetLines_CimsCostCodeId");

                    b.HasIndex("BudgetRevisionId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_BudgetLines_Revision_LineNumber");

                    b.ToTable("BudgetLines", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Budgets.BudgetRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_BudgetRevisions_Budget_RevisionNumber");

                    b.ToTable("BudgetRevisions", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Commitments.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ActivatedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ClosedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CounterpartyCimsOrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<Guid>("FinancialsProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyCimsOrganisationId")
                        .HasDatabaseName("IX_Commitments_Counterparty");

                    b.HasIndex("FinancialsProjectId", "Type", "Reference")
                        .IsUnique()
                        .HasDatabaseName("UX_Commitments_Project_Type_Reference");

                    b.ToTable("Commitments", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Commitments.CommitmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CimsCostCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CimsCostCodeId")
                        .HasDatabaseName("IX_CommitmentLines_CimsCostCodeId");

                    b.HasIndex("CommitmentId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_CommitmentLines_Commitment_LineNumber");

                    b.ToTable("CommitmentLines", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Projects.FinancialsProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CimsProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CimsProjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_FinancialsProjects_CimsProjectId");

                    b.ToTable("FinancialsProjects", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Projects.ProjectCommercialConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("FinancialsProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialsProjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProjectCommercialConfigurations_FinancialsProjectId");

                    b.ToTable("ProjectCommercialConfigurations", "fin");
                });

            modelBuilder.Entity("Financials.Infrastructure.Inbox.InboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_InboxEvents_EventId");

                    b.ToTable("InboxEvents", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Budgets.Budget", b =>
                {
                    b.HasOne("Financials.Domain.Projects.FinancialsProject", null)
                        .WithOne()
                        .HasForeignKey("Financials.Domain.Budgets.Budget", "FinancialsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Financials.Domain.Budgets.BudgetLine", b =>
                {
                    b.HasOne("Financials.Domain.Budgets.BudgetRevision", null)
                        .WithMany("Lines")
                        .HasForeignKey("BudgetRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Financials.Domain.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BudgetLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("AmountValue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("AmountCurrency")
                                .IsFixedLength();

                            b1.HasKey("BudgetLineId");

                            b1.ToTable("BudgetLines", "fin");

                            b1.WithOwner()
                                .HasForeignKey("BudgetLineId");
                        });

                    b.OwnsOne("Financials.Domain.Common.Money", "UnitRate", b1 =>
                        {
                            b1.Property<Guid>("BudgetLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UnitRateAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("UnitRateCurrency")
                                .IsFixedLength();

                            b1.HasKey("BudgetLineId");

                            b1.ToTable("BudgetLines", "fin");

                            b1.WithOwner()
                                .HasForeignKey("BudgetLineId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("UnitRate")
                        .IsRequired();
                });

            modelBuilder.Entity("Financials.Domain.Budgets.BudgetRevision", b =>
                {
                    b.HasOne("Financials.Domain.Budgets.Budget", null)
                        .WithMany("Revisions")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Financials.Domain.Commitments.Commitment", b =>
                {
                    b.HasOne("Financials.Domain.Projects.FinancialsProject", null)
                        .WithMany()
                        .HasForeignKey("FinancialsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Financials.Domain.Projects.PaymentTerms", "PaymentTermsOverride", b1 =>
                        {
                            b1.Property<Guid>("CommitmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DueDayOfMonth")
                                .HasColumnType("int")
                                .HasColumnName("PaymentOverrideDueDayOfMonth");

                            b1.Property<int>("NetDays")
                                .HasColumnType("int")
                                .HasColumnName("PaymentOverrideNetDays");

                            b1.Property<int>("PaymentCycleDays")
                                .HasColumnType("int")
                                .HasColumnName("PaymentOverrideCycleDays");

                            b1.HasKey("CommitmentId");

                            b1.ToTable("Commitments", "fin");

                            b1.WithOwner()
                                .HasForeignKey("CommitmentId");
                        });

                    b.OwnsOne("Financials.Domain.Projects.RetentionScheme", "RetentionOverride", b1 =>
                        {
                            b1.Property<Guid>("CommitmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionOverridePercentage");

                            b1.Property<decimal>("ReleaseAtDLPEndPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionOverrideReleaseAtDLPEndPercentage");

                            b1.Property<decimal>("ReleaseAtPCPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionOverrideReleaseAtPCPercentage");

                            b1.HasKey("CommitmentId");

                            b1.ToTable("Commitments", "fin");

                            b1.WithOwner()
                                .HasForeignKey("CommitmentId");
                        });

                    b.Navigation("PaymentTermsOverride");

                    b.Navigation("RetentionOverride");
                });

            modelBuilder.Entity("Financials.Domain.Commitments.CommitmentLine", b =>
                {
                    b.HasOne("Financials.Domain.Commitments.Commitment", null)
                        .WithMany("Lines")
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Financials.Domain.Common.Money", "UnitRate", b1 =>
                        {
                            b1.Property<Guid>("CommitmentLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UnitRateAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("UnitRateCurrency")
                                .IsFixedLength();

                            b1.HasKey("CommitmentLineId");

                            b1.ToTable("CommitmentLines", "fin");

                            b1.WithOwner()
                                .HasForeignKey("CommitmentLineId");
                        });

                    b.OwnsOne("Financials.Domain.Common.Money", "Value", b1 =>
                        {
                            b1.Property<Guid>("CommitmentLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("ValueAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("ValueCurrency")
                                .IsFixedLength();

                            b1.HasKey("CommitmentLineId");

                            b1.ToTable("CommitmentLines", "fin");

                            b1.WithOwner()
                                .HasForeignKey("CommitmentLineId");
                        });

                    b.Navigation("UnitRate")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Financials.Domain.Projects.ProjectCommercialConfiguration", b =>
                {
                    b.HasOne("Financials.Domain.Projects.FinancialsProject", null)
                        .WithOne()
                        .HasForeignKey("Financials.Domain.Projects.ProjectCommercialConfiguration", "FinancialsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Financials.Domain.Projects.OverCommitmentGuard", "OverCommitmentGuard", b1 =>
                        {
                            b1.Property<Guid>("ProjectCommercialConfigurationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Mode")
                                .HasColumnType("int")
                                .HasColumnName("OverCommitmentGuardMode");

                            b1.HasKey("ProjectCommercialConfigurationId");

                            b1.ToTable("ProjectCommercialConfigurations", "fin");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCommercialConfigurationId");
                        });

                    b.OwnsOne("Financials.Domain.Projects.PaymentTerms", "PaymentTerms", b1 =>
                        {
                            b1.Property<Guid>("ProjectCommercialConfigurationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DueDayOfMonth")
                                .HasColumnType("int")
                                .HasColumnName("PaymentDueDayOfMonth");

                            b1.Property<int>("NetDays")
                                .HasColumnType("int")
                                .HasColumnName("PaymentNetDays");

                            b1.Property<int>("PaymentCycleDays")
                                .HasColumnType("int")
                                .HasColumnName("PaymentCycleDays");

                            b1.HasKey("ProjectCommercialConfigurationId");

                            b1.ToTable("ProjectCommercialConfigurations", "fin");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCommercialConfigurationId");
                        });

                    b.OwnsOne("Financials.Domain.Projects.RetentionScheme", "RetentionScheme", b1 =>
                        {
                            b1.Property<Guid>("ProjectCommercialConfigurationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionPercentage");

                            b1.Property<decimal>("ReleaseAtDLPEndPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionReleaseAtDLPEndPercentage");

                            b1.Property<decimal>("ReleaseAtPCPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionReleaseAtPCPercentage");

                            b1.HasKey("ProjectCommercialConfigurationId");

                            b1.ToTable("ProjectCommercialConfigurations", "fin");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCommercialConfigurationId");
                        });

                    b.Navigation("OverCommitmentGuard")
                        .IsRequired();

                    b.Navigation("PaymentTerms")
                        .IsRequired();

                    b.Navigation("RetentionScheme")
                        .IsRequired();
                });

            modelBuilder.Entity("Financials.Domain.Budgets.Budget", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Financials.Domain.Budgets.BudgetRevision", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Financials.Domain.Commitments.Commitment", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
