// <auto-generated />
using System;
using Financials.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financials.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancialsDbContext))]
    [Migration("20260508130345_AddProjectCommercialConfigurations")]
    partial class AddProjectCommercialConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fin")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Financials.Domain.Projects.FinancialsProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CimsProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CimsProjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_FinancialsProjects_CimsProjectId");

                    b.ToTable("FinancialsProjects", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Projects.ProjectCommercialConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("FinancialsProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialsProjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProjectCommercialConfigurations_FinancialsProjectId");

                    b.ToTable("ProjectCommercialConfigurations", "fin");
                });

            modelBuilder.Entity("Financials.Domain.Projects.ProjectCommercialConfiguration", b =>
                {
                    b.HasOne("Financials.Domain.Projects.FinancialsProject", null)
                        .WithOne()
                        .HasForeignKey("Financials.Domain.Projects.ProjectCommercialConfiguration", "FinancialsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Financials.Domain.Projects.PaymentTerms", "PaymentTerms", b1 =>
                        {
                            b1.Property<Guid>("ProjectCommercialConfigurationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DueDayOfMonth")
                                .HasColumnType("int")
                                .HasColumnName("PaymentDueDayOfMonth");

                            b1.Property<int>("NetDays")
                                .HasColumnType("int")
                                .HasColumnName("PaymentNetDays");

                            b1.Property<int>("PaymentCycleDays")
                                .HasColumnType("int")
                                .HasColumnName("PaymentCycleDays");

                            b1.HasKey("ProjectCommercialConfigurationId");

                            b1.ToTable("ProjectCommercialConfigurations", "fin");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCommercialConfigurationId");
                        });

                    b.OwnsOne("Financials.Domain.Projects.RetentionScheme", "RetentionScheme", b1 =>
                        {
                            b1.Property<Guid>("ProjectCommercialConfigurationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionPercentage");

                            b1.Property<decimal>("ReleaseAtDLPEndPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionReleaseAtDLPEndPercentage");

                            b1.Property<decimal>("ReleaseAtPCPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RetentionReleaseAtPCPercentage");

                            b1.HasKey("ProjectCommercialConfigurationId");

                            b1.ToTable("ProjectCommercialConfigurations", "fin");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCommercialConfigurationId");
                        });

                    b.Navigation("PaymentTerms")
                        .IsRequired();

                    b.Navigation("RetentionScheme")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
